name: dncnn_stop
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2019.11.28=hecc5488_0
  - certifi=2019.11.28=py37_0
  - cloudpickle=1.2.2=py_1
  - cytoolz=0.10.1=py37h516909a_0
  - dask-core=2.9.0=py_0
  - imageio=2.6.1=py37_0
  - matplotlib-base=3.1.1=py37hfd891ef_0
  - networkx=2.4=py_0
  - openssl=1.1.1d=h516909a_0
  - pywavelets=1.1.1=py37hc1659b7_0
  - scikit-image=0.16.2=py37hb3f55d8_0
  - tk=8.6.10=hed695b0_0
  - toolz=0.10.0=py_0
  - _libgcc_mutex=0.1=main
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - cffi=1.13.2=py37h2e261b9_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cycler=0.10.0=py37_0
  - dbus=1.13.12=h746ee38_0
  - decorator=4.4.1=py_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.63.1=h5a9c865_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.9.0=py37h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.4=243
  - ipython=7.10.2=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - jedi=0.15.1=py37_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.1.0=py37he6710b0_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - matplotlib=3.1.1=py37h5429711_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.17.4=py37hc1035e2_0
  - numpy-base=1.17.4=py37hde5b4d6_0
  - olefile=0.46=py_0
  - pandas=0.25.3=py37he6710b0_0
  - parso=0.5.2=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pillow=6.2.1=py37h34e0f95_0
  - pip=19.3.1=py37_0
  - prompt_toolkit=3.0.2=py_0
  - ptyprocess=0.6.0=py37_0
  - pycparser=2.19=py_0
  - pygments=2.5.2=py_0
  - pyparsing=2.4.5=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - python=3.7.5=h0371630_0
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - scipy=1.3.2=py37h7c811a0_0
  - setuptools=42.0.2=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.13.0=py37_0
  - sqlite=3.30.1=h7b6447c_0
  - tornado=6.0.3=py37h7b6447c_0
  - tqdm=4.40.2=py_0
  - traitlets=4.3.3=py37_0
  - wcwidth=0.1.7=py37_0
  - wheel=0.33.6=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pytorch=1.3.1=py3.7_cuda10.1.243_cudnn7.6.3_0
  - torchvision=0.4.2=py37_cu101
  - pip:
    - dask==2.9.0
    - opencv-python==4.1.2.30
    - protobuf==3.11.2
    - tensorboardx==1.9
    - torch==1.3.1


